export enum AppRoutes {
    Landing = "/",
    About = "/about",
    AboutUs = "/aboutUs",
    Home = "/home",
    Team = "/team",
    TheTeam = "/theteam",
    Contact = "/contact",
    Mission = "/mission",
    GeneralInfo = "/generalInfo",
    Location = "/location",
    Properties = "/properties",
    PropertyDetail = "/properties/:uid",
    Messenger = "/messenger",
    Dashboard = "/dashboard",
    AvgPrice = "/avg-price",
    Companies = "/companies",
    Login = "/login",
    SignUp = "/sign-up",
    Approvals = "/approvals",
    Contracts = "/contracts",
}
